#cloud-config
package_upgrade: true

packages:
  - bind9
  - bind9utils

write_files:
  - owner: root:bind
    path: /etc/bind/named.conf.options
    content: |
        acl rfc1918 {
            10.0.0.0/8;
            192.168.0.0/16;
        };

        options {
            directory "/var/cache/bind";

            dnssec-validation auto;

            listen-on-v6 { any; };
            recursion yes;
            allow-query { rfc1918; };
        };

runcmd:
  - [ systemctl, enable, bind9.service ]
  - [ systemctl, restart, bind9.service ]